permalink: /:year:month:day/:title
url: awesomejedie.github.io #Your url here
baseurl: /project

# variables
name: AwesomeJediE
description: This is a webpage owned and operated by an AwesomeJediE, a.k.a. Emma, a.k.a. emmamatronics, a.k.a. EmmaNotEmma. I may get a little silly. Goofy, even. Witness and enjoy.
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true
